### ISSUE TITLE
[1.19.2] issue with icon selection

### ISSUE THREAD

**Issue by zISKo666** [McJtyMods/SignTastic#5]
Hello McJty,

In version 2.1.2 on 1.19.2 there is an issue with the "Icon" selector at the bottom right.
It always seems to be black and it's difficult to choose the icon you want.
![grafik](https://user-images.githubusercontent.com/6992216/230928118-95d3f837-8bb8-465a-812d-010f85760778.png)

Have a nice day
zISKo

**Comment by McJty** [comment]
I'll check it out

**Comment by McJty** [comment]
Fixed in the next version
